export const SET_USER_COORDINATES_STR = "SET_USER_COORDINATES_STR";
export const SET_USER_COORDINATES = "SET_USER_COORDINATES";
export const SET_USER_VALUES = "SET_USER_VALUES";
export const SET_MAX_USER_VALUE = "SET_MAX_USER_VALUE";
