export const FETCH_ORGANISMS = 'FETCH_ORGANISMS'
export const FETCH_STAMMS = 'FETCH_STAMMS_FOR_ORG'
export const FETCH_CONTIGS = 'FETCH_CONTIGS_FOR_ORG_STAMM'
export const FETCH_COMPLEXITY = 'FETCH_COMPLEXITY'
export const PUT_SELECTION = 'PUT_SELECTION'

export const FETCH_GRAPH = 'FETCH_GRAPH'
export const FETCH_WINDOWS = 'FETCH_WINDOWS'